sudo: required
dist: trusty
language: node_js
node_js:
- stable
branches:
  except:
  - gh-pages
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install
script:
- echo "This design module has no tests"
after_success:
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -k "$DEPLOYSECRET"
  -in deploy.enc -out deploy_key -d; fi
- cd $TRAVIS_BUILD_DIR/scripts
- chmod 755 ghp.sh
- "./ghp.sh"
env:
  global:
  - secure: oj2G4GpMbrFGdIf24fnTUtr1nU/h3w7sCTuj4C9iHNHlVHvXMR2JVs/ZvywbEyKq2iKmtSSKFb538/rkecZpUc4SAJ02bc7vYGXACLPkb4hFB4IoE21LsAgXIYhyFDMahraT/PtuxYPWhFeXpEidXeNWTT9hKjzQaBrXyl1kXcB0pxfUzCqKYHKRlUaWIbFsCapz4JLQRtjkW5T9Ge8qvtujFwfqnTNodeNjmIN6+iveu9CHv8Z/52C9MTrPfnszMiIYoDnqigSvCCzaCjvh+0eGBhiTuNdqmOK4yQkMK1wQgoTTlzmr6X3kNRs+7zvnrWVi7DjUqUgRUD+3lqg+pUgbnUMCQqbboZ12SU2Eyat0OgV6IxeGwTozHqt3NxxLu8SFdjRfz8CxRDFCOp/7Iw7qn6xX2DjyDLdvpHJWeUiEalG7QnHmhMJEIxvHBwR/FB80gGwI6/P4c22jXZZfuVzZ3NW2SPJ9mF1zvccRBKxLDUoQpK/yOspWEj8TjWCipqZs5boTrwUoD+KfioN0pzxPpro3JszZLtgNa+8uQCT1nDjCgGK7kcLN1DtYGrFy6M5Wyll++a+7FTgNAFdZvunmqdnIvUHjcy+9vVTqGwODwi8Iu5hdSWJc2/iX1HwqM6OTHl8LjduPhg3p9o7dvNoQaiT7l8Dq+nieyCfpc4w=
  - secure: L69hk05duxOkypxafSTvgZrOCVNj6mz6AbKBvCr9maLSyzPhM0+eFSQbjyA+ehpxetboW37gZsbiQ4OmDCnkCmSvgg8u1c2hJfdSUy2aBFrPyuhVl/FoOpjxx1gjXg6jQA51PT38DPPrHro4foACucNmVUpDvJFkEg8J2b3KIpsotHLl36PKrXdG0zhGvFGgsCTslcRkvcEaXkN3R5vjNHTvGadNn2xgDagsgNOBF/sau5FceLRwPPbwvVzHK2n/R+mYOk1C7q8wYqVlKcmkdMifr+yTsWniEeF6Bym+MyekQz0O7iWcAUiJJG3nqmQ9YtH4IwebuBTjeJalUpL8nxatCCd2RhGv9p78i6Fw4DDvlg1dcQlvC1JHVXQ8jYpF+Pu/VGifO7FRl16ekdNNt71ZSroNPEvlz10J8/Dgrp8piqI04m/4V0z/skS/GLAXPizMBficW+F0oJWN4xGCA2UoDD1+ZHSm9+K71uNQPzxfVshMr5nz7e5bgEc50/oIi6zISupFi0He1R2zfVe8pD005/Isn8m7UHSvOvUc2dCIOpPvQlMCC9XpwgpZKIzMKM4K1R7qIb7bQRRUQwISCqDt8/fzSTtsWYUzwyTivGrpz8KUgsNZM5l2DUB2XBtSbr4gljWgoorCZhTyN8kXZYNqDH6jjRC9ziU1aw9M9Dk=
